apiVersion: cnap.platforms.howlabs.io/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  envPrefix:
    - env: Development
      prefix: dev
    - env: Integration
      prefix: integ
    - env: Staging
      prefix: staging
  exposedAPIs:
    - name: LoginService
      urlPath: /login
      httpsEnabled: false
      authentication:
        enabled: true
        basicAuth: true
        apiToken: true
      singleSignOn:
        enabled: true
        saml: true
        oauth2: true
        oidc: true