apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # The name is always in the form: <plural>.<group>
  name: applications.cnap.platforms.howlabs.io

spec:
  group: cnap.platforms.howlabs.io
  names:
    kind: Application
    plural: applications
    singular: application
    shortNames:
    - app
    - apps
  # Namespaced or Cluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    # each version can be enabled or disabled for serving with served
    served: true
    # each version can be marked as the storage version with storage
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Used as prefix for all exposed API URLs. For e.g.
              # For exposed API: exampleapp.io/createuser, the URL will be:
              # For Dev Env:          If envPrefix is "dev"         : dev.exampleapp.io/createuser
              # For Integration Env:  If envPrefix is "integ"       : integ.exampleapp.io/createuser
              # For Staging Env:      If envPrefix is "staging      : staging.exampleapp.io/createuser
              # For Production Env:   No Prefix for Production Env  : exampleapp.io/createuser
              envPrefix:
                type: array
                items:
                  type: object
                  properties:
                    env:
                      type: string
                    prefix:
                      type: string
              exposedAPIs:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    urlPath:
                      type: string
                    httpsEnabled:
                      type: boolean
                    whitelistIPs:
                      type: array
                      items:
                        type: string
                    authentication:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        basicAuth:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                            username:
                              type: string
                            password:
                              type: string
                        apiToken:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                            token:
                              type: string
                    singleSignOn:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        saml:
                          type: object
                          properties:
                            clientID:
                              type: string
                            clientSecret:
                              type: string
                            idpMetadata:
                              type: string
                            assertionConsumerServiceURL:
                              type: string
              internalAPIs:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    urlPath:
                      type: string
              upstreamAPIs:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    urlPath:
                      type: string
          status:
            type: object
            properties:
              acceptedNames:
                type: object
                properties:
                  plural:
                    type: string
                  singular:
                    type: string
                  kind:
                    type: string
                  listKind:
                    type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string